apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: withdoggy
    app.kubernetes.io/component: api-gateway
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/withdoggy/withdoggy/cmd/api-gateway